# Generated by Django 5.0.1 on 2024-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_post_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('science', 'Science'), ('travel', 'Travel'), ('finance', 'Finance'), ('relationships', 'Relationships'), ('beauty', 'Beauty'), ('fashion', 'Fashion'), ('education', 'Education'), ('healthy', 'Healthy')], max_length=50),
        ),
    ]
